### ISSUE TITLE
What accounts on Twitter actually notify you on your phone? What other things commonly give you notifications?

### ISSUE THREAD

**Issue by aretecode** [greydnls/ama#19]

**Comment by greydnls** [comment]
I have notifications set up for @kayladnls, @codemanifesto, @phpwomen. 

Other notifications: The norm. Text messages, emails, calendar. I have facebook notifications turned off. Words with friends very annoyingly updates me way too frequently to nag me about games that are expiring because I suck at keeping up with things. 

I also set an inordinate amount of alarms to keep me on schedule throughout the day. (Wake up, get kids, start dinner, start bedtime routine, etc).
