### ISSUE TITLE
What tools do you use on a daily basis?

### ISSUE THREAD

**Issue by arthurvr** [greydnls/ama#2]

**Comment by greydnls** [comment]
For development? 
1. PHPStorm
2. Terminal
3. Git/Github
4. Jira (at work). I use an app called Bee for that, because it makes it more tolerable. 

I do primarily Backend work, so that's pretty much all I need. I access mysql through the command line, so I don't have a workbench/gui for that. 

When I'm working on side projects, I usually use Trello for project management because it's much slimmer/less feature rich than Jira, which I enjoy. 

Waffle.io is also a good PM tool, as it utilizes PRs and Issues from GH to manage things. 

For non work things: Twitter, Slack, Inbox (for email), Mou for editing Markdown, gitodo for todo lists, disco for learning things.
