### ISSUE TITLE
Higher education in engineering for your kids

### ISSUE THREAD

**Issue by blainsmith** [greydnls/ama#24]
As an engineer with a 2 year old son I wonder what he will grow up to be interested in when he decides on a career. If he decides to get into computer science or engineering I will find it hard to justify the cost of college 16 years from now to study a subject which can, for the most part, be studied for free given the amount of resources available online. I understand the need for a degree for doctors, lawyers, and some other professions, but for computer science it seems like less and less of a requirement as time goes on. I attended 3 different private schools trying to find the right flavor of engineering to set myself up for a job, but in the end I dropped out and just studied on my own. Now I am a founding engineer of 2 businesses. I haven't applied anything I learned in the 6 years I went to college, but, unfortunately, I have the loans to prove it. :smile:

As parents we want our kids to have all the opportunities we had and more, but without the financial burden. Since you have kids of your own I was wondering what you view on college will be in their future if they decide to follow in your footsteps?

**Comment by greydnls** [comment]
If my children want to be engineers I will highly encourage them to go to a 2 year college (I'll do this regardless of their specialty). They're not going to learn anything related to Engineering, but I think it's a good thing to have to wade through those few years of humanities, and english and science. I think it makes people a little bit more rounded. 

They'll also (probably) be able to get a few foundational classes in in that time that DO apply to CS. Past that, I would encourage them to use existing resources and just start DOING it. I don't think degrees are necessary and I'm not going to force my kids to get them. 

That said, I think our kids have some things that we never had. If you're my age or older, having a computer at home when you were a tiny person was very rare. I was lucky enough to have grown up with one since I was 2 or so, but most people didn't. 

Our kids, though? I have 4 laptops, two external monitors, we have 3 smart phones in our house and a few tablets. They have technology at the tip of their fingers all day long. So, if my kids show any interest in engineering (and they already have), they'll start learning young. As in now. By the time they get to college age, they should at least know most of what I know now, or so I hope. 

Also, I find it worth mentioning that all of the above positions and advice are exactly the same for my daughter, even though the question was directed at my sons.

**Comment by blainsmith** [comment]
I completely agree with all of that and I would like to clarify that I actually only thought you had 2 sons. :smile: I read that in a previous post. Title changed!

I'm 33 so I only got introduced to my first computer when I was in my late childhood/early teens and I was hooked since then. I have been preparing for when he gets older with books and games I found on Kickstarter that help kids understand programming, but most importantly analytical thinking and problem solving. Too often I come across people who cannot think their way out of a simple problem. The 2 year basic science and liberal arts track is a great option since it definitely makes you a well rounded person, but also saved a lot of money. I wish I went that route when I started, but live and learn.
