### ISSUE TITLE
bipolar

### ISSUE THREAD

**Issue by ghost** [greydnls/ama#4]
How do you keep working when you're experiencing a depressive episode? 

How do you keep moving forward when you want to give up?

**Comment by greydnls** [comment]
My job is very understanding of the needs of their team. When I just can't even at the office, I stay home and work from there. It's hard to be productive, but I manage. Tasks that I should have been able to do in a normal working day will take me most of the day to finish because I take frequent breaks. 

When I'm feeling down, I shower a lot. Like 3-4 a day. I don't know why, but it helps. I also cry in the shower, so that probably helps too. 

I see a psychiatrist 1-2/month, and I take Lamictal daily. It helps to stabilize my mood some. 

Moving forward for me is either easier or harder (I don't know which) because I have kids. I'm a single mom now, and they need me. Failure isn't an option. Refusing to get out of bed isn't an option. Whether I want to or not, whether I feel like I can take it or not, I HAVE to. They need me, and they deserve me to try as hard as I can. 

When all of that fails, I have the best friends in the world. They listen to me rant and rave and cry and they remind me that there is good in the world and that occasionally I can be a part of that good. It helps a lot.
